package net.nettape.connection;

import java.io.*;

public enum Command {
	LOGIN, LOGOUT, SENDBACKUPSET, RECEIVEBACKUPSET, RECEIVEBACKUPSETS, SENDBACKUP, RECEIVEBACKUP, SENDBACKUPITEM, RECEIVEBACKUPITEM, SENDFILE, RECEIVEFILE, 
	RECEIVECHECKSUMS, SENDDELTAS, SENDRESTORE, RECEIVERESTORE, SENDRESTOREITEM, RECEIVERESTOREITEM, SENDUSER, RECEIVEUSER, SENDCLIENT, 
	SENDSETTINGS, RECEIVESETTINGS, SENDSCHEDULE, RECEIVESCHEDULE, RECEIVESCHEDULES, SENDMESSAGE, SENDCDP, SENDCDPITEM,
	CHECKBACKUPSETVERSION, RECEIVEBACKUPS, NOOP, RECEIVELOGS
}

