// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package nettapeshadow;

@net.sf.jni4net.attributes.ClrType
public class ShadowCopy extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected ShadowCopy(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public ShadowCopy() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        nettapeshadow.ShadowCopy.__ctorShadowCopy0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorShadowCopy0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)Z")
    public native boolean StartVolume(java.lang.String strVolume);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;)Z")
    public native boolean CopyFile(java.lang.String strSourceFile, java.lang.String strDestDir);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void StopVolume();
    
    public static system.Type typeof() {
        return nettapeshadow.ShadowCopy.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        nettapeshadow.ShadowCopy.staticType = staticType;
    }
    //</generated-proxy>
}
