//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NettapeShadow {
    
    
    #region Component Designer generated code 
    public partial class ShadowCopy_ {
        
        public new static global::java.lang.Class _class {
            get {
                return global::NettapeShadow.@__ShadowCopy.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::NettapeShadow.ShadowCopy))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::NettapeShadow.ShadowCopy))]
    internal sealed partial class @__ShadowCopy : global::java.lang.Object {
        
        internal static global::java.lang.Class staticClass;
        
        protected @__ShadowCopy(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::NettapeShadow.@__ShadowCopy.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__ShadowCopy);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "StartVolume", "StartVolume0", "(Ljava/lang/String;)Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "CopyFile", "CopyFile1", "(Ljava/lang/String;Ljava/lang/String;)Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "StopVolume", "StopVolume2", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorShadowCopy0", "__ctorShadowCopy0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static bool StartVolume0(global::System.IntPtr @__envp, global::System.IntPtr @__obj, global::System.IntPtr strVolume) {
            // (Ljava/lang/String;)Z
            // (LSystem/String;)Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::NettapeShadow.ShadowCopy @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::NettapeShadow.ShadowCopy>(@__env, @__obj);
            return ((bool)(@__real.StartVolume(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, strVolume))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return default(bool);
        }
        
        private static bool CopyFile1(global::System.IntPtr @__envp, global::System.IntPtr @__obj, global::System.IntPtr strSourceFile, global::System.IntPtr strDestDir) {
            // (Ljava/lang/String;Ljava/lang/String;)Z
            // (LSystem/String;LSystem/String;)Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::NettapeShadow.ShadowCopy @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::NettapeShadow.ShadowCopy>(@__env, @__obj);
            return ((bool)(@__real.CopyFile(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, strSourceFile), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, strDestDir))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return default(bool);
        }
        
        private static void StopVolume2(global::System.IntPtr @__envp, global::System.IntPtr @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::NettapeShadow.ShadowCopy @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::NettapeShadow.ShadowCopy>(@__env, @__obj);
            @__real.StopVolume();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorShadowCopy0(global::System.IntPtr @__envp, global::System.IntPtr @__class, global::System.IntPtr @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::NettapeShadow.ShadowCopy @__real = new global::NettapeShadow.ShadowCopy();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::NettapeShadow.@__ShadowCopy(@__env);
            }
        }
    }
    #endregion
}
