package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Adgroup generated by hbm2java
 */
public class Adgroup  implements java.io.Serializable {


     private Integer adgroupid;
     private String name;
     private Set reluserAdgroups = new HashSet(0);
     private Set reluserAdgroups_1 = new HashSet(0);
     private Set advertisements = new HashSet(0);
     private Set advertisements_1 = new HashSet(0);

    public Adgroup() {
    }

    public Adgroup(String name, Set reluserAdgroups, Set reluserAdgroups_1, Set advertisements, Set advertisements_1) {
       this.name = name;
       this.reluserAdgroups = reluserAdgroups;
       this.reluserAdgroups_1 = reluserAdgroups_1;
       this.advertisements = advertisements;
       this.advertisements_1 = advertisements_1;
    }
   
    public Integer getAdgroupid() {
        return this.adgroupid;
    }
    
    public void setAdgroupid(Integer adgroupid) {
        this.adgroupid = adgroupid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getReluserAdgroups() {
        return this.reluserAdgroups;
    }
    
    public void setReluserAdgroups(Set reluserAdgroups) {
        this.reluserAdgroups = reluserAdgroups;
    }
    public Set getReluserAdgroups_1() {
        return this.reluserAdgroups_1;
    }
    
    public void setReluserAdgroups_1(Set reluserAdgroups_1) {
        this.reluserAdgroups_1 = reluserAdgroups_1;
    }
    public Set getAdvertisements() {
        return this.advertisements;
    }
    
    public void setAdvertisements(Set advertisements) {
        this.advertisements = advertisements;
    }
    public Set getAdvertisements_1() {
        return this.advertisements_1;
    }
    
    public void setAdvertisements_1(Set advertisements_1) {
        this.advertisements_1 = advertisements_1;
    }




}


