package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Advertisement generated by hbm2java
 */
public class Advertisement  implements java.io.Serializable {


     private Integer advertisementid;
     private Adgroup adgroup;
     private String name;
     private String text;
     private Date startdate;
     private Integer popularity;
     private Long hits;
     private Long clicks;
     private Integer hitsperday;
     private Integer clicksperday;
     private Integer time;
     private Integer order;
     private String gifimage;
     private String flashimage;
     private String target;
     private Set adviews = new HashSet(0);
     private Set adviews_1 = new HashSet(0);

    public Advertisement() {
    }

    public Advertisement(Adgroup adgroup, String name, String text, Date startdate, Integer popularity, Long hits, Long clicks, Integer hitsperday, Integer clicksperday, Integer time, Integer order, String gifimage, String flashimage, String target, Set adviews, Set adviews_1) {
       this.adgroup = adgroup;
       this.name = name;
       this.text = text;
       this.startdate = startdate;
       this.popularity = popularity;
       this.hits = hits;
       this.clicks = clicks;
       this.hitsperday = hitsperday;
       this.clicksperday = clicksperday;
       this.time = time;
       this.order = order;
       this.gifimage = gifimage;
       this.flashimage = flashimage;
       this.target = target;
       this.adviews = adviews;
       this.adviews_1 = adviews_1;
    }
   
    public Integer getAdvertisementid() {
        return this.advertisementid;
    }
    
    public void setAdvertisementid(Integer advertisementid) {
        this.advertisementid = advertisementid;
    }
    public Adgroup getAdgroup() {
        return this.adgroup;
    }
    
    public void setAdgroup(Adgroup adgroup) {
        this.adgroup = adgroup;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Integer getPopularity() {
        return this.popularity;
    }
    
    public void setPopularity(Integer popularity) {
        this.popularity = popularity;
    }
    public Long getHits() {
        return this.hits;
    }
    
    public void setHits(Long hits) {
        this.hits = hits;
    }
    public Long getClicks() {
        return this.clicks;
    }
    
    public void setClicks(Long clicks) {
        this.clicks = clicks;
    }
    public Integer getHitsperday() {
        return this.hitsperday;
    }
    
    public void setHitsperday(Integer hitsperday) {
        this.hitsperday = hitsperday;
    }
    public Integer getClicksperday() {
        return this.clicksperday;
    }
    
    public void setClicksperday(Integer clicksperday) {
        this.clicksperday = clicksperday;
    }
    public Integer getTime() {
        return this.time;
    }
    
    public void setTime(Integer time) {
        this.time = time;
    }
    public Integer getOrder() {
        return this.order;
    }
    
    public void setOrder(Integer order) {
        this.order = order;
    }
    public String getGifimage() {
        return this.gifimage;
    }
    
    public void setGifimage(String gifimage) {
        this.gifimage = gifimage;
    }
    public String getFlashimage() {
        return this.flashimage;
    }
    
    public void setFlashimage(String flashimage) {
        this.flashimage = flashimage;
    }
    public String getTarget() {
        return this.target;
    }
    
    public void setTarget(String target) {
        this.target = target;
    }
    public Set getAdviews() {
        return this.adviews;
    }
    
    public void setAdviews(Set adviews) {
        this.adviews = adviews;
    }
    public Set getAdviews_1() {
        return this.adviews_1;
    }
    
    public void setAdviews_1(Set adviews_1) {
        this.adviews_1 = adviews_1;
    }




}


