package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Adview generated by hbm2java
 */
public class Adview  implements java.io.Serializable {


     private Integer adviewid;
     private Advertisement advertisement;
     private Client client;
     private Date datetime;
     private String ipaddress;

    public Adview() {
    }

    public Adview(Advertisement advertisement, Client client, Date datetime, String ipaddress) {
       this.advertisement = advertisement;
       this.client = client;
       this.datetime = datetime;
       this.ipaddress = ipaddress;
    }
   
    public Integer getAdviewid() {
        return this.adviewid;
    }
    
    public void setAdviewid(Integer adviewid) {
        this.adviewid = adviewid;
    }
    public Advertisement getAdvertisement() {
        return this.advertisement;
    }
    
    public void setAdvertisement(Advertisement advertisement) {
        this.advertisement = advertisement;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public String getIpaddress() {
        return this.ipaddress;
    }
    
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }




}


