package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Backupset generated by hbm2java
 */
public class Backupset  implements java.io.Serializable {


     private Integer backupsetid;
     private long version;
     private Client client;
     private String name;
     private Date datecreated;
     private Date datedeleted;
     private Date datedeactivated;
     private Boolean active;
     private Boolean deleted;
     private Boolean retention;
     private Boolean filepermissions;
     private Boolean continuousprotection;
     private Integer cpinterval;
     private Short type;
     private Boolean isdeltas;
     private Short sort;
     private Integer infiledeltablocksize;
     private Integer infiledeltamaxsize;
     private Boolean volumeshadowcopy;
     private Boolean offlinebackup;
     private Boolean snapshotcomplete;
     private Boolean enableencryption;
     private Boolean enablecompression;
     private Integer infiledeltaminsize;
     private Set retentionschedules = new HashSet(0);
     private Set schedules = new HashSet(0);
     private Set backups = new HashSet(0);
     private Set backups_1 = new HashSet(0);
     private Set schedules_1 = new HashSet(0);
     private Set filters = new HashSet(0);
     private Set backupcommands = new HashSet(0);
     private Set iprestrictions = new HashSet(0);
     private Set backupsetitems = new HashSet(0);
     private Set backupcommands_1 = new HashSet(0);
     private Set iprestrictions_1 = new HashSet(0);
     private Set filters_1 = new HashSet(0);
     private Set backupsetitems_1 = new HashSet(0);
     private Set retentionschedules_1 = new HashSet(0);

    public Backupset() {
    }

    public Backupset(Client client, String name, Date datecreated, Date datedeleted, Date datedeactivated, Boolean active, Boolean deleted, Boolean retention, Boolean filepermissions, Boolean continuousprotection, Integer cpinterval, Short type, Boolean isdeltas, Short sort, Integer infiledeltablocksize, Integer infiledeltamaxsize, Boolean volumeshadowcopy, Boolean offlinebackup, Boolean snapshotcomplete, Boolean enableencryption, Boolean enablecompression, Integer infiledeltaminsize, Set retentionschedules, Set schedules, Set backups, Set backups_1, Set schedules_1, Set filters, Set backupcommands, Set iprestrictions, Set backupsetitems, Set backupcommands_1, Set iprestrictions_1, Set filters_1, Set backupsetitems_1, Set retentionschedules_1) {
       this.client = client;
       this.name = name;
       this.datecreated = datecreated;
       this.datedeleted = datedeleted;
       this.datedeactivated = datedeactivated;
       this.active = active;
       this.deleted = deleted;
       this.retention = retention;
       this.filepermissions = filepermissions;
       this.continuousprotection = continuousprotection;
       this.cpinterval = cpinterval;
       this.type = type;
       this.isdeltas = isdeltas;
       this.sort = sort;
       this.infiledeltablocksize = infiledeltablocksize;
       this.infiledeltamaxsize = infiledeltamaxsize;
       this.volumeshadowcopy = volumeshadowcopy;
       this.offlinebackup = offlinebackup;
       this.snapshotcomplete = snapshotcomplete;
       this.enableencryption = enableencryption;
       this.enablecompression = enablecompression;
       this.infiledeltaminsize = infiledeltaminsize;
       this.retentionschedules = retentionschedules;
       this.schedules = schedules;
       this.backups = backups;
       this.backups_1 = backups_1;
       this.schedules_1 = schedules_1;
       this.filters = filters;
       this.backupcommands = backupcommands;
       this.iprestrictions = iprestrictions;
       this.backupsetitems = backupsetitems;
       this.backupcommands_1 = backupcommands_1;
       this.iprestrictions_1 = iprestrictions_1;
       this.filters_1 = filters_1;
       this.backupsetitems_1 = backupsetitems_1;
       this.retentionschedules_1 = retentionschedules_1;
    }
   
    public Integer getBackupsetid() {
        return this.backupsetid;
    }
    
    public void setBackupsetid(Integer backupsetid) {
        this.backupsetid = backupsetid;
    }
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDatecreated() {
        return this.datecreated;
    }
    
    public void setDatecreated(Date datecreated) {
        this.datecreated = datecreated;
    }
    public Date getDatedeleted() {
        return this.datedeleted;
    }
    
    public void setDatedeleted(Date datedeleted) {
        this.datedeleted = datedeleted;
    }
    public Date getDatedeactivated() {
        return this.datedeactivated;
    }
    
    public void setDatedeactivated(Date datedeactivated) {
        this.datedeactivated = datedeactivated;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Boolean getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
    public Boolean getRetention() {
        return this.retention;
    }
    
    public void setRetention(Boolean retention) {
        this.retention = retention;
    }
    public Boolean getFilepermissions() {
        return this.filepermissions;
    }
    
    public void setFilepermissions(Boolean filepermissions) {
        this.filepermissions = filepermissions;
    }
    public Boolean getContinuousprotection() {
        return this.continuousprotection;
    }
    
    public void setContinuousprotection(Boolean continuousprotection) {
        this.continuousprotection = continuousprotection;
    }
    public Integer getCpinterval() {
        return this.cpinterval;
    }
    
    public void setCpinterval(Integer cpinterval) {
        this.cpinterval = cpinterval;
    }
    public Short getType() {
        return this.type;
    }
    
    public void setType(Short type) {
        this.type = type;
    }
    public Boolean getIsdeltas() {
        return this.isdeltas;
    }
    
    public void setIsdeltas(Boolean isdeltas) {
        this.isdeltas = isdeltas;
    }
    public Short getSort() {
        return this.sort;
    }
    
    public void setSort(Short sort) {
        this.sort = sort;
    }
    public Integer getInfiledeltablocksize() {
        return this.infiledeltablocksize;
    }
    
    public void setInfiledeltablocksize(Integer infiledeltablocksize) {
        this.infiledeltablocksize = infiledeltablocksize;
    }
    public Integer getInfiledeltamaxsize() {
        return this.infiledeltamaxsize;
    }
    
    public void setInfiledeltamaxsize(Integer infiledeltamaxsize) {
        this.infiledeltamaxsize = infiledeltamaxsize;
    }
    public Boolean getVolumeshadowcopy() {
        return this.volumeshadowcopy;
    }
    
    public void setVolumeshadowcopy(Boolean volumeshadowcopy) {
        this.volumeshadowcopy = volumeshadowcopy;
    }
    public Boolean getOfflinebackup() {
        return this.offlinebackup;
    }
    
    public void setOfflinebackup(Boolean offlinebackup) {
        this.offlinebackup = offlinebackup;
    }
    public Boolean getSnapshotcomplete() {
        return this.snapshotcomplete;
    }
    
    public void setSnapshotcomplete(Boolean snapshotcomplete) {
        this.snapshotcomplete = snapshotcomplete;
    }
    public Boolean getEnableencryption() {
        return this.enableencryption;
    }
    
    public void setEnableencryption(Boolean enableencryption) {
        this.enableencryption = enableencryption;
    }
    public Boolean getEnablecompression() {
        return this.enablecompression;
    }
    
    public void setEnablecompression(Boolean enablecompression) {
        this.enablecompression = enablecompression;
    }
    public Integer getInfiledeltaminsize() {
        return this.infiledeltaminsize;
    }
    
    public void setInfiledeltaminsize(Integer infiledeltaminsize) {
        this.infiledeltaminsize = infiledeltaminsize;
    }
    public Set getRetentionschedules() {
        return this.retentionschedules;
    }
    
    public void setRetentionschedules(Set retentionschedules) {
        this.retentionschedules = retentionschedules;
    }
    public Set getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set schedules) {
        this.schedules = schedules;
    }
    public Set getBackups() {
        return this.backups;
    }
    
    public void setBackups(Set backups) {
        this.backups = backups;
    }
    public Set getBackups_1() {
        return this.backups_1;
    }
    
    public void setBackups_1(Set backups_1) {
        this.backups_1 = backups_1;
    }
    public Set getSchedules_1() {
        return this.schedules_1;
    }
    
    public void setSchedules_1(Set schedules_1) {
        this.schedules_1 = schedules_1;
    }
    public Set getFilters() {
        return this.filters;
    }
    
    public void setFilters(Set filters) {
        this.filters = filters;
    }
    public Set getBackupcommands() {
        return this.backupcommands;
    }
    
    public void setBackupcommands(Set backupcommands) {
        this.backupcommands = backupcommands;
    }
    public Set getIprestrictions() {
        return this.iprestrictions;
    }
    
    public void setIprestrictions(Set iprestrictions) {
        this.iprestrictions = iprestrictions;
    }
    public Set getBackupsetitems() {
        return this.backupsetitems;
    }
    
    public void setBackupsetitems(Set backupsetitems) {
        this.backupsetitems = backupsetitems;
    }
    public Set getBackupcommands_1() {
        return this.backupcommands_1;
    }
    
    public void setBackupcommands_1(Set backupcommands_1) {
        this.backupcommands_1 = backupcommands_1;
    }
    public Set getIprestrictions_1() {
        return this.iprestrictions_1;
    }
    
    public void setIprestrictions_1(Set iprestrictions_1) {
        this.iprestrictions_1 = iprestrictions_1;
    }
    public Set getFilters_1() {
        return this.filters_1;
    }
    
    public void setFilters_1(Set filters_1) {
        this.filters_1 = filters_1;
    }
    public Set getBackupsetitems_1() {
        return this.backupsetitems_1;
    }
    
    public void setBackupsetitems_1(Set backupsetitems_1) {
        this.backupsetitems_1 = backupsetitems_1;
    }
    public Set getRetentionschedules_1() {
        return this.retentionschedules_1;
    }
    
    public void setRetentionschedules_1(Set retentionschedules_1) {
        this.retentionschedules_1 = retentionschedules_1;
    }




}


