package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1



/**
 * Backupsetitem generated by hbm2java
 */
public class Backupsetitem  implements java.io.Serializable {


     private Integer backupsetitemid;
     private Backupset backupset;
     private String path;
     private Short type;
     private Boolean backup;
     private Boolean isfolder;
     private String root;
     private Integer lastbackupid;
     private Long lastbackupitemlocation;
     private Long lastbackupitemlength;
     private Integer snapshotbackupid;
     private Long snapshotbackupitemlocation;
     private Long snapshotbackupitemlength;

    public Backupsetitem() {
    }

    public Backupsetitem(Backupset backupset, String path, Short type, Boolean backup, Boolean isfolder, String root, Integer lastbackupid, Long lastbackupitemlocation, Long lastbackupitemlength, Integer snapshotbackupid, Long snapshotbackupitemlocation, Long snapshotbackupitemlength) {
       this.backupset = backupset;
       this.path = path;
       this.type = type;
       this.backup = backup;
       this.isfolder = isfolder;
       this.root = root;
       this.lastbackupid = lastbackupid;
       this.lastbackupitemlocation = lastbackupitemlocation;
       this.lastbackupitemlength = lastbackupitemlength;
       this.snapshotbackupid = snapshotbackupid;
       this.snapshotbackupitemlocation = snapshotbackupitemlocation;
       this.snapshotbackupitemlength = snapshotbackupitemlength;
    }
   
    public Integer getBackupsetitemid() {
        return this.backupsetitemid;
    }
    
    public void setBackupsetitemid(Integer backupsetitemid) {
        this.backupsetitemid = backupsetitemid;
    }
    public Backupset getBackupset() {
        return this.backupset;
    }
    
    public void setBackupset(Backupset backupset) {
        this.backupset = backupset;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public Short getType() {
        return this.type;
    }
    
    public void setType(Short type) {
        this.type = type;
    }
    public Boolean getBackup() {
        return this.backup;
    }
    
    public void setBackup(Boolean backup) {
        this.backup = backup;
    }
    public Boolean getIsfolder() {
        return this.isfolder;
    }
    
    public void setIsfolder(Boolean isfolder) {
        this.isfolder = isfolder;
    }
    public String getRoot() {
        return this.root;
    }
    
    public void setRoot(String root) {
        this.root = root;
    }
    public Integer getLastbackupid() {
        return this.lastbackupid;
    }
    
    public void setLastbackupid(Integer lastbackupid) {
        this.lastbackupid = lastbackupid;
    }
    public Long getLastbackupitemlocation() {
        return this.lastbackupitemlocation;
    }
    
    public void setLastbackupitemlocation(Long lastbackupitemlocation) {
        this.lastbackupitemlocation = lastbackupitemlocation;
    }
    public Long getLastbackupitemlength() {
        return this.lastbackupitemlength;
    }
    
    public void setLastbackupitemlength(Long lastbackupitemlength) {
        this.lastbackupitemlength = lastbackupitemlength;
    }
    public Integer getSnapshotbackupid() {
        return this.snapshotbackupid;
    }
    
    public void setSnapshotbackupid(Integer snapshotbackupid) {
        this.snapshotbackupid = snapshotbackupid;
    }
    public Long getSnapshotbackupitemlocation() {
        return this.snapshotbackupitemlocation;
    }
    
    public void setSnapshotbackupitemlocation(Long snapshotbackupitemlocation) {
        this.snapshotbackupitemlocation = snapshotbackupitemlocation;
    }
    public Long getSnapshotbackupitemlength() {
        return this.snapshotbackupitemlength;
    }
    
    public void setSnapshotbackupitemlength(Long snapshotbackupitemlength) {
        this.snapshotbackupitemlength = snapshotbackupitemlength;
    }




}


