package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Backupitem generated by hbm2java
 */
public class Backupitem  implements java.io.Serializable {


     private Integer backupitemid;
     private Integer version;
     private Integer backupid;
     private Integer backupsetitemid;
     private String path;
     private Short type;
     private Date datetime;
     private Long position;
     private Long length;
     private Boolean isdeltas;
     private String root;
     private Integer statusid;
     private Boolean isfolder;
     private Set restoreitems = new HashSet(0);
     private Set restoreitems_1 = new HashSet(0);

    public Backupitem() {
    }

    public Backupitem(Integer backupid, Integer backupsetitemid, String path, Short type, Date datetime, Long position, Long length, Boolean isdeltas, String root, Integer statusid, Boolean isfolder, Set restoreitems, Set restoreitems_1) {
       this.backupid = backupid;
       this.backupsetitemid = backupsetitemid;
       this.path = path;
       this.type = type;
       this.datetime = datetime;
       this.position = position;
       this.length = length;
       this.isdeltas = isdeltas;
       this.root = root;
       this.statusid = statusid;
       this.isfolder = isfolder;
       this.restoreitems = restoreitems;
       this.restoreitems_1 = restoreitems_1;
    }
   
    public Integer getBackupitemid() {
        return this.backupitemid;
    }
    
    public void setBackupitemid(Integer backupitemid) {
        this.backupitemid = backupitemid;
    }
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    public Integer getBackupid() {
        return this.backupid;
    }
    
    public void setBackupid(Integer backupid) {
        this.backupid = backupid;
    }
    public Integer getBackupsetitemid() {
        return this.backupsetitemid;
    }
    
    public void setBackupsetitemid(Integer backupsetitemid) {
        this.backupsetitemid = backupsetitemid;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public Short getType() {
        return this.type;
    }
    
    public void setType(Short type) {
        this.type = type;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public Long getPosition() {
        return this.position;
    }
    
    public void setPosition(Long position) {
        this.position = position;
    }
    public Long getLength() {
        return this.length;
    }
    
    public void setLength(Long length) {
        this.length = length;
    }
    public Boolean getIsdeltas() {
        return this.isdeltas;
    }
    
    public void setIsdeltas(Boolean isdeltas) {
        this.isdeltas = isdeltas;
    }
    public String getRoot() {
        return this.root;
    }
    
    public void setRoot(String root) {
        this.root = root;
    }
    public Integer getStatusid() {
        return this.statusid;
    }
    
    public void setStatusid(Integer statusid) {
        this.statusid = statusid;
    }
    public Boolean getIsfolder() {
        return this.isfolder;
    }
    
    public void setIsfolder(Boolean isfolder) {
        this.isfolder = isfolder;
    }
    public Set getRestoreitems() {
        return this.restoreitems;
    }
    
    public void setRestoreitems(Set restoreitems) {
        this.restoreitems = restoreitems;
    }
    public Set getRestoreitems_1() {
        return this.restoreitems_1;
    }
    
    public void setRestoreitems_1(Set restoreitems_1) {
        this.restoreitems_1 = restoreitems_1;
    }




}


