package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1



/**
 * Backupcommand generated by hbm2java
 */
public class Backupcommand  implements java.io.Serializable {


     private Integer backupcommandid;
     private Backupset backupset;
     private Boolean type;
     private String name;
     private String command;
     private String workingfolder;

    public Backupcommand() {
    }

	
    public Backupcommand(Backupset backupset) {
        this.backupset = backupset;
    }
    public Backupcommand(Backupset backupset, Boolean type, String name, String command, String workingfolder) {
       this.backupset = backupset;
       this.type = type;
       this.name = name;
       this.command = command;
       this.workingfolder = workingfolder;
    }
   
    public Integer getBackupcommandid() {
        return this.backupcommandid;
    }
    
    public void setBackupcommandid(Integer backupcommandid) {
        this.backupcommandid = backupcommandid;
    }
    public Backupset getBackupset() {
        return this.backupset;
    }
    
    public void setBackupset(Backupset backupset) {
        this.backupset = backupset;
    }
    public Boolean getType() {
        return this.type;
    }
    
    public void setType(Boolean type) {
        this.type = type;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCommand() {
        return this.command;
    }
    
    public void setCommand(String command) {
        this.command = command;
    }
    public String getWorkingfolder() {
        return this.workingfolder;
    }
    
    public void setWorkingfolder(String workingfolder) {
        this.workingfolder = workingfolder;
    }




}


