package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Backup generated by hbm2java
 */
public class Backup  implements java.io.Serializable {


     private Integer backupid;
     private Status status;
     private Backupset backupset;
     private String name;
     private Date datetime;
     private Date datetimeended;
     private Integer serverid;
     private String ipaddress;
     private Integer lastbackupitemid;
     private Boolean iscdp;
     private Short type;
     private Boolean filepermissions;

    public Backup() {
    }

    public Backup(Status status, Backupset backupset, String name, Date datetime, Date datetimeended, Integer serverid, String ipaddress, Integer lastbackupitemid, Boolean iscdp, Short type, Boolean filepermissions) {
       this.status = status;
       this.backupset = backupset;
       this.name = name;
       this.datetime = datetime;
       this.datetimeended = datetimeended;
       this.serverid = serverid;
       this.ipaddress = ipaddress;
       this.lastbackupitemid = lastbackupitemid;
       this.iscdp = iscdp;
       this.type = type;
       this.filepermissions = filepermissions;
    }
   
    public Integer getBackupid() {
        return this.backupid;
    }
    
    public void setBackupid(Integer backupid) {
        this.backupid = backupid;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public Backupset getBackupset() {
        return this.backupset;
    }
    
    public void setBackupset(Backupset backupset) {
        this.backupset = backupset;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public Date getDatetimeended() {
        return this.datetimeended;
    }
    
    public void setDatetimeended(Date datetimeended) {
        this.datetimeended = datetimeended;
    }
    public Integer getServerid() {
        return this.serverid;
    }
    
    public void setServerid(Integer serverid) {
        this.serverid = serverid;
    }
    public String getIpaddress() {
        return this.ipaddress;
    }
    
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }
    public Integer getLastbackupitemid() {
        return this.lastbackupitemid;
    }
    
    public void setLastbackupitemid(Integer lastbackupitemid) {
        this.lastbackupitemid = lastbackupitemid;
    }
    public Boolean getIscdp() {
        return this.iscdp;
    }
    
    public void setIscdp(Boolean iscdp) {
        this.iscdp = iscdp;
    }
    public Short getType() {
        return this.type;
    }
    
    public void setType(Short type) {
        this.type = type;
    }
    public Boolean getFilepermissions() {
        return this.filepermissions;
    }
    
    public void setFilepermissions(Boolean filepermissions) {
        this.filepermissions = filepermissions;
    }




}


