package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1



/**
 * Backuphistory generated by hbm2java
 */
public class Backuphistory  implements java.io.Serializable {


     private BackuphistoryId id;
     private Integer backupid;
     private Long location;
     private Long length;

    public Backuphistory() {
    }

	
    public Backuphistory(BackuphistoryId id) {
        this.id = id;
    }
    public Backuphistory(BackuphistoryId id, Integer backupid, Long location, Long length) {
       this.id = id;
       this.backupid = backupid;
       this.location = location;
       this.length = length;
    }
   
    public BackuphistoryId getId() {
        return this.id;
    }
    
    public void setId(BackuphistoryId id) {
        this.id = id;
    }
    public Integer getBackupid() {
        return this.backupid;
    }
    
    public void setBackupid(Integer backupid) {
        this.backupid = backupid;
    }
    public Long getLocation() {
        return this.location;
    }
    
    public void setLocation(Long location) {
        this.location = location;
    }
    public Long getLength() {
        return this.length;
    }
    
    public void setLength(Long length) {
        this.length = length;
    }




}


