package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer clientid;
     private User user;
     private String guid;
     private Integer type;
     private String name;
     private Set backupsets = new HashSet(0);
     private Set adviews = new HashSet(0);
     private Set adviews_1 = new HashSet(0);
     private Set logs = new HashSet(0);
     private Set logs_1 = new HashSet(0);
     private Set backupsets_1 = new HashSet(0);

    public Client() {
    }

    public Client(User user, String guid, Integer type, String name, Set backupsets, Set adviews, Set adviews_1, Set logs, Set logs_1, Set backupsets_1) {
       this.user = user;
       this.guid = guid;
       this.type = type;
       this.name = name;
       this.backupsets = backupsets;
       this.adviews = adviews;
       this.adviews_1 = adviews_1;
       this.logs = logs;
       this.logs_1 = logs_1;
       this.backupsets_1 = backupsets_1;
    }
   
    public Integer getClientid() {
        return this.clientid;
    }
    
    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getGuid() {
        return this.guid;
    }
    
    public void setGuid(String guid) {
        this.guid = guid;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getBackupsets() {
        return this.backupsets;
    }
    
    public void setBackupsets(Set backupsets) {
        this.backupsets = backupsets;
    }
    public Set getAdviews() {
        return this.adviews;
    }
    
    public void setAdviews(Set adviews) {
        this.adviews = adviews;
    }
    public Set getAdviews_1() {
        return this.adviews_1;
    }
    
    public void setAdviews_1(Set adviews_1) {
        this.adviews_1 = adviews_1;
    }
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }
    public Set getLogs_1() {
        return this.logs_1;
    }
    
    public void setLogs_1(Set logs_1) {
        this.logs_1 = logs_1;
    }
    public Set getBackupsets_1() {
        return this.backupsets_1;
    }
    
    public void setBackupsets_1(Set backupsets_1) {
        this.backupsets_1 = backupsets_1;
    }




}


