package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1



/**
 * Criteria generated by hbm2java
 */
public class Criteria  implements java.io.Serializable {


     private Integer criteriaid;
     private Filter filter;
     private String pattern;
     private Short type;
     private Boolean matchcase;

    public Criteria() {
    }

    public Criteria(Filter filter, String pattern, Short type, Boolean matchcase) {
       this.filter = filter;
       this.pattern = pattern;
       this.type = type;
       this.matchcase = matchcase;
    }
   
    public Integer getCriteriaid() {
        return this.criteriaid;
    }
    
    public void setCriteriaid(Integer criteriaid) {
        this.criteriaid = criteriaid;
    }
    public Filter getFilter() {
        return this.filter;
    }
    
    public void setFilter(Filter filter) {
        this.filter = filter;
    }
    public String getPattern() {
        return this.pattern;
    }
    
    public void setPattern(String pattern) {
        this.pattern = pattern;
    }
    public Short getType() {
        return this.type;
    }
    
    public void setType(Short type) {
        this.type = type;
    }
    public Boolean getMatchcase() {
        return this.matchcase;
    }
    
    public void setMatchcase(Boolean matchcase) {
        this.matchcase = matchcase;
    }




}


