package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Filter generated by hbm2java
 */
public class Filter  implements java.io.Serializable {


     private Integer filterid;
     private Restore restore;
     private Backupset backupset;
     private String name;
     private Boolean include;
     private String toppath;
     private Boolean applytofolders;
     private Boolean applytofiles;
     private Set criterias = new HashSet(0);
     private Set criterias_1 = new HashSet(0);

    public Filter() {
    }

    public Filter(Restore restore, Backupset backupset, String name, Boolean include, String toppath, Boolean applytofolders, Boolean applytofiles, Set criterias, Set criterias_1) {
       this.restore = restore;
       this.backupset = backupset;
       this.name = name;
       this.include = include;
       this.toppath = toppath;
       this.applytofolders = applytofolders;
       this.applytofiles = applytofiles;
       this.criterias = criterias;
       this.criterias_1 = criterias_1;
    }
   
    public Integer getFilterid() {
        return this.filterid;
    }
    
    public void setFilterid(Integer filterid) {
        this.filterid = filterid;
    }
    public Restore getRestore() {
        return this.restore;
    }
    
    public void setRestore(Restore restore) {
        this.restore = restore;
    }
    public Backupset getBackupset() {
        return this.backupset;
    }
    
    public void setBackupset(Backupset backupset) {
        this.backupset = backupset;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Boolean getInclude() {
        return this.include;
    }
    
    public void setInclude(Boolean include) {
        this.include = include;
    }
    public String getToppath() {
        return this.toppath;
    }
    
    public void setToppath(String toppath) {
        this.toppath = toppath;
    }
    public Boolean getApplytofolders() {
        return this.applytofolders;
    }
    
    public void setApplytofolders(Boolean applytofolders) {
        this.applytofolders = applytofolders;
    }
    public Boolean getApplytofiles() {
        return this.applytofiles;
    }
    
    public void setApplytofiles(Boolean applytofiles) {
        this.applytofiles = applytofiles;
    }
    public Set getCriterias() {
        return this.criterias;
    }
    
    public void setCriterias(Set criterias) {
        this.criterias = criterias;
    }
    public Set getCriterias_1() {
        return this.criterias_1;
    }
    
    public void setCriterias_1(Set criterias_1) {
        this.criterias_1 = criterias_1;
    }




}


