package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Jobsettings generated by hbm2java
 */
public class Jobsettings  implements java.io.Serializable {


     private Integer jobsettingsid;
     private Boolean backupreport;
     private Boolean restorereport;
     private Boolean settingchangereport;
     private Boolean missedbackupreport;
     private Boolean inactiveuserreport;
     private Long inactiveuserreportdays;
     private Boolean offlinebackupreminder;
     private Date inactiveuserreporttime;
     private Long offlinebackupreminderdays;
     private Date offlinebackupremindertime;
     private Boolean backupquotareminder;
     private Long backupquotareminderdays;
     private Date backupquotaremindertime;
     private Integer backupquotareminderpercentage;
     private Boolean trialuserreminder;
     private Long trialuserreminderdays;
     private Date trialuserremindertime;
     private Integer trialuserreminderdaysafterregistration;
     private Boolean usagereport;
     private Long usagereportdays;
     private Date usagereporttime;
     private Boolean errorreport;
     private Long errorreportdays;
     private Date errorreporttime;
     private Boolean inactiveuserremoval;
     private Long inactiveuserremovaldays;
     private Date inactiveuserremovaltime;
     private Boolean retentionpolicyjob;
     private Long retentionpolicyjobdays;
     private Date retentionpolicyjobtime;
     private Boolean systemlogremoval;
     private Long systemlogremovaldays;
     private Date systemlogremovaltime;
     private Boolean debuglogremoval;
     private Long debuglogremovaldays;
     private Date debuglogremovaltime;

    public Jobsettings() {
    }

    public Jobsettings(Boolean backupreport, Boolean restorereport, Boolean settingchangereport, Boolean missedbackupreport, Boolean inactiveuserreport, Long inactiveuserreportdays, Boolean offlinebackupreminder, Date inactiveuserreporttime, Long offlinebackupreminderdays, Date offlinebackupremindertime, Boolean backupquotareminder, Long backupquotareminderdays, Date backupquotaremindertime, Integer backupquotareminderpercentage, Boolean trialuserreminder, Long trialuserreminderdays, Date trialuserremindertime, Integer trialuserreminderdaysafterregistration, Boolean usagereport, Long usagereportdays, Date usagereporttime, Boolean errorreport, Long errorreportdays, Date errorreporttime, Boolean inactiveuserremoval, Long inactiveuserremovaldays, Date inactiveuserremovaltime, Boolean retentionpolicyjob, Long retentionpolicyjobdays, Date retentionpolicyjobtime, Boolean systemlogremoval, Long systemlogremovaldays, Date systemlogremovaltime, Boolean debuglogremoval, Long debuglogremovaldays, Date debuglogremovaltime) {
       this.backupreport = backupreport;
       this.restorereport = restorereport;
       this.settingchangereport = settingchangereport;
       this.missedbackupreport = missedbackupreport;
       this.inactiveuserreport = inactiveuserreport;
       this.inactiveuserreportdays = inactiveuserreportdays;
       this.offlinebackupreminder = offlinebackupreminder;
       this.inactiveuserreporttime = inactiveuserreporttime;
       this.offlinebackupreminderdays = offlinebackupreminderdays;
       this.offlinebackupremindertime = offlinebackupremindertime;
       this.backupquotareminder = backupquotareminder;
       this.backupquotareminderdays = backupquotareminderdays;
       this.backupquotaremindertime = backupquotaremindertime;
       this.backupquotareminderpercentage = backupquotareminderpercentage;
       this.trialuserreminder = trialuserreminder;
       this.trialuserreminderdays = trialuserreminderdays;
       this.trialuserremindertime = trialuserremindertime;
       this.trialuserreminderdaysafterregistration = trialuserreminderdaysafterregistration;
       this.usagereport = usagereport;
       this.usagereportdays = usagereportdays;
       this.usagereporttime = usagereporttime;
       this.errorreport = errorreport;
       this.errorreportdays = errorreportdays;
       this.errorreporttime = errorreporttime;
       this.inactiveuserremoval = inactiveuserremoval;
       this.inactiveuserremovaldays = inactiveuserremovaldays;
       this.inactiveuserremovaltime = inactiveuserremovaltime;
       this.retentionpolicyjob = retentionpolicyjob;
       this.retentionpolicyjobdays = retentionpolicyjobdays;
       this.retentionpolicyjobtime = retentionpolicyjobtime;
       this.systemlogremoval = systemlogremoval;
       this.systemlogremovaldays = systemlogremovaldays;
       this.systemlogremovaltime = systemlogremovaltime;
       this.debuglogremoval = debuglogremoval;
       this.debuglogremovaldays = debuglogremovaldays;
       this.debuglogremovaltime = debuglogremovaltime;
    }
   
    public Integer getJobsettingsid() {
        return this.jobsettingsid;
    }
    
    public void setJobsettingsid(Integer jobsettingsid) {
        this.jobsettingsid = jobsettingsid;
    }
    public Boolean getBackupreport() {
        return this.backupreport;
    }
    
    public void setBackupreport(Boolean backupreport) {
        this.backupreport = backupreport;
    }
    public Boolean getRestorereport() {
        return this.restorereport;
    }
    
    public void setRestorereport(Boolean restorereport) {
        this.restorereport = restorereport;
    }
    public Boolean getSettingchangereport() {
        return this.settingchangereport;
    }
    
    public void setSettingchangereport(Boolean settingchangereport) {
        this.settingchangereport = settingchangereport;
    }
    public Boolean getMissedbackupreport() {
        return this.missedbackupreport;
    }
    
    public void setMissedbackupreport(Boolean missedbackupreport) {
        this.missedbackupreport = missedbackupreport;
    }
    public Boolean getInactiveuserreport() {
        return this.inactiveuserreport;
    }
    
    public void setInactiveuserreport(Boolean inactiveuserreport) {
        this.inactiveuserreport = inactiveuserreport;
    }
    public Long getInactiveuserreportdays() {
        return this.inactiveuserreportdays;
    }
    
    public void setInactiveuserreportdays(Long inactiveuserreportdays) {
        this.inactiveuserreportdays = inactiveuserreportdays;
    }
    public Boolean getOfflinebackupreminder() {
        return this.offlinebackupreminder;
    }
    
    public void setOfflinebackupreminder(Boolean offlinebackupreminder) {
        this.offlinebackupreminder = offlinebackupreminder;
    }
    public Date getInactiveuserreporttime() {
        return this.inactiveuserreporttime;
    }
    
    public void setInactiveuserreporttime(Date inactiveuserreporttime) {
        this.inactiveuserreporttime = inactiveuserreporttime;
    }
    public Long getOfflinebackupreminderdays() {
        return this.offlinebackupreminderdays;
    }
    
    public void setOfflinebackupreminderdays(Long offlinebackupreminderdays) {
        this.offlinebackupreminderdays = offlinebackupreminderdays;
    }
    public Date getOfflinebackupremindertime() {
        return this.offlinebackupremindertime;
    }
    
    public void setOfflinebackupremindertime(Date offlinebackupremindertime) {
        this.offlinebackupremindertime = offlinebackupremindertime;
    }
    public Boolean getBackupquotareminder() {
        return this.backupquotareminder;
    }
    
    public void setBackupquotareminder(Boolean backupquotareminder) {
        this.backupquotareminder = backupquotareminder;
    }
    public Long getBackupquotareminderdays() {
        return this.backupquotareminderdays;
    }
    
    public void setBackupquotareminderdays(Long backupquotareminderdays) {
        this.backupquotareminderdays = backupquotareminderdays;
    }
    public Date getBackupquotaremindertime() {
        return this.backupquotaremindertime;
    }
    
    public void setBackupquotaremindertime(Date backupquotaremindertime) {
        this.backupquotaremindertime = backupquotaremindertime;
    }
    public Integer getBackupquotareminderpercentage() {
        return this.backupquotareminderpercentage;
    }
    
    public void setBackupquotareminderpercentage(Integer backupquotareminderpercentage) {
        this.backupquotareminderpercentage = backupquotareminderpercentage;
    }
    public Boolean getTrialuserreminder() {
        return this.trialuserreminder;
    }
    
    public void setTrialuserreminder(Boolean trialuserreminder) {
        this.trialuserreminder = trialuserreminder;
    }
    public Long getTrialuserreminderdays() {
        return this.trialuserreminderdays;
    }
    
    public void setTrialuserreminderdays(Long trialuserreminderdays) {
        this.trialuserreminderdays = trialuserreminderdays;
    }
    public Date getTrialuserremindertime() {
        return this.trialuserremindertime;
    }
    
    public void setTrialuserremindertime(Date trialuserremindertime) {
        this.trialuserremindertime = trialuserremindertime;
    }
    public Integer getTrialuserreminderdaysafterregistration() {
        return this.trialuserreminderdaysafterregistration;
    }
    
    public void setTrialuserreminderdaysafterregistration(Integer trialuserreminderdaysafterregistration) {
        this.trialuserreminderdaysafterregistration = trialuserreminderdaysafterregistration;
    }
    public Boolean getUsagereport() {
        return this.usagereport;
    }
    
    public void setUsagereport(Boolean usagereport) {
        this.usagereport = usagereport;
    }
    public Long getUsagereportdays() {
        return this.usagereportdays;
    }
    
    public void setUsagereportdays(Long usagereportdays) {
        this.usagereportdays = usagereportdays;
    }
    public Date getUsagereporttime() {
        return this.usagereporttime;
    }
    
    public void setUsagereporttime(Date usagereporttime) {
        this.usagereporttime = usagereporttime;
    }
    public Boolean getErrorreport() {
        return this.errorreport;
    }
    
    public void setErrorreport(Boolean errorreport) {
        this.errorreport = errorreport;
    }
    public Long getErrorreportdays() {
        return this.errorreportdays;
    }
    
    public void setErrorreportdays(Long errorreportdays) {
        this.errorreportdays = errorreportdays;
    }
    public Date getErrorreporttime() {
        return this.errorreporttime;
    }
    
    public void setErrorreporttime(Date errorreporttime) {
        this.errorreporttime = errorreporttime;
    }
    public Boolean getInactiveuserremoval() {
        return this.inactiveuserremoval;
    }
    
    public void setInactiveuserremoval(Boolean inactiveuserremoval) {
        this.inactiveuserremoval = inactiveuserremoval;
    }
    public Long getInactiveuserremovaldays() {
        return this.inactiveuserremovaldays;
    }
    
    public void setInactiveuserremovaldays(Long inactiveuserremovaldays) {
        this.inactiveuserremovaldays = inactiveuserremovaldays;
    }
    public Date getInactiveuserremovaltime() {
        return this.inactiveuserremovaltime;
    }
    
    public void setInactiveuserremovaltime(Date inactiveuserremovaltime) {
        this.inactiveuserremovaltime = inactiveuserremovaltime;
    }
    public Boolean getRetentionpolicyjob() {
        return this.retentionpolicyjob;
    }
    
    public void setRetentionpolicyjob(Boolean retentionpolicyjob) {
        this.retentionpolicyjob = retentionpolicyjob;
    }
    public Long getRetentionpolicyjobdays() {
        return this.retentionpolicyjobdays;
    }
    
    public void setRetentionpolicyjobdays(Long retentionpolicyjobdays) {
        this.retentionpolicyjobdays = retentionpolicyjobdays;
    }
    public Date getRetentionpolicyjobtime() {
        return this.retentionpolicyjobtime;
    }
    
    public void setRetentionpolicyjobtime(Date retentionpolicyjobtime) {
        this.retentionpolicyjobtime = retentionpolicyjobtime;
    }
    public Boolean getSystemlogremoval() {
        return this.systemlogremoval;
    }
    
    public void setSystemlogremoval(Boolean systemlogremoval) {
        this.systemlogremoval = systemlogremoval;
    }
    public Long getSystemlogremovaldays() {
        return this.systemlogremovaldays;
    }
    
    public void setSystemlogremovaldays(Long systemlogremovaldays) {
        this.systemlogremovaldays = systemlogremovaldays;
    }
    public Date getSystemlogremovaltime() {
        return this.systemlogremovaltime;
    }
    
    public void setSystemlogremovaltime(Date systemlogremovaltime) {
        this.systemlogremovaltime = systemlogremovaltime;
    }
    public Boolean getDebuglogremoval() {
        return this.debuglogremoval;
    }
    
    public void setDebuglogremoval(Boolean debuglogremoval) {
        this.debuglogremoval = debuglogremoval;
    }
    public Long getDebuglogremovaldays() {
        return this.debuglogremovaldays;
    }
    
    public void setDebuglogremovaldays(Long debuglogremovaldays) {
        this.debuglogremovaldays = debuglogremovaldays;
    }
    public Date getDebuglogremovaltime() {
        return this.debuglogremovaltime;
    }
    
    public void setDebuglogremovaltime(Date debuglogremovaltime) {
        this.debuglogremovaltime = debuglogremovaltime;
    }




}


