package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1



/**
 * Languagesettings generated by hbm2java
 */
public class Languagesettings  implements java.io.Serializable {


     private Integer languagesettingsid;
     private Settings settings;
     private Language language;

    public Languagesettings() {
    }

    public Languagesettings(Settings settings, Language language) {
       this.settings = settings;
       this.language = language;
    }
   
    public Integer getLanguagesettingsid() {
        return this.languagesettingsid;
    }
    
    public void setLanguagesettingsid(Integer languagesettingsid) {
        this.languagesettingsid = languagesettingsid;
    }
    public Settings getSettings() {
        return this.settings;
    }
    
    public void setSettings(Settings settings) {
        this.settings = settings;
    }
    public Language getLanguage() {
        return this.language;
    }
    
    public void setLanguage(Language language) {
        this.language = language;
    }




}


