package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * License generated by hbm2java
 */
public class License  implements java.io.Serializable {


     private Integer licenseid;
     private String licenseename;
     private String licensekey;
     private String companyname;
     private String contactname;
     private String contactphone;
     private Integer ebcclientquota;
     private Integer bbcclientquota;
     private Integer exchangeserverquota;
     private Integer exchangemailboxquota;
     private Integer sqlserverquota;
     private Integer oraclequota;
     private Integer mysqlquota;
     private Integer lotusdominoquota;
     private Integer lotusnotesquota;
     private Integer infiledeltaquota;
     private Integer volumshadowcopyquota;
     private Boolean bosreplicationmodule;
     private Date expirydate;
     private Date freeupgradeuntil;

    public License() {
    }

    public License(String licenseename, String licensekey, String companyname, String contactname, String contactphone, Integer ebcclientquota, Integer bbcclientquota, Integer exchangeserverquota, Integer exchangemailboxquota, Integer sqlserverquota, Integer oraclequota, Integer mysqlquota, Integer lotusdominoquota, Integer lotusnotesquota, Integer infiledeltaquota, Integer volumshadowcopyquota, Boolean bosreplicationmodule, Date expirydate, Date freeupgradeuntil) {
       this.licenseename = licenseename;
       this.licensekey = licensekey;
       this.companyname = companyname;
       this.contactname = contactname;
       this.contactphone = contactphone;
       this.ebcclientquota = ebcclientquota;
       this.bbcclientquota = bbcclientquota;
       this.exchangeserverquota = exchangeserverquota;
       this.exchangemailboxquota = exchangemailboxquota;
       this.sqlserverquota = sqlserverquota;
       this.oraclequota = oraclequota;
       this.mysqlquota = mysqlquota;
       this.lotusdominoquota = lotusdominoquota;
       this.lotusnotesquota = lotusnotesquota;
       this.infiledeltaquota = infiledeltaquota;
       this.volumshadowcopyquota = volumshadowcopyquota;
       this.bosreplicationmodule = bosreplicationmodule;
       this.expirydate = expirydate;
       this.freeupgradeuntil = freeupgradeuntil;
    }
   
    public Integer getLicenseid() {
        return this.licenseid;
    }
    
    public void setLicenseid(Integer licenseid) {
        this.licenseid = licenseid;
    }
    public String getLicenseename() {
        return this.licenseename;
    }
    
    public void setLicenseename(String licenseename) {
        this.licenseename = licenseename;
    }
    public String getLicensekey() {
        return this.licensekey;
    }
    
    public void setLicensekey(String licensekey) {
        this.licensekey = licensekey;
    }
    public String getCompanyname() {
        return this.companyname;
    }
    
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }
    public String getContactname() {
        return this.contactname;
    }
    
    public void setContactname(String contactname) {
        this.contactname = contactname;
    }
    public String getContactphone() {
        return this.contactphone;
    }
    
    public void setContactphone(String contactphone) {
        this.contactphone = contactphone;
    }
    public Integer getEbcclientquota() {
        return this.ebcclientquota;
    }
    
    public void setEbcclientquota(Integer ebcclientquota) {
        this.ebcclientquota = ebcclientquota;
    }
    public Integer getBbcclientquota() {
        return this.bbcclientquota;
    }
    
    public void setBbcclientquota(Integer bbcclientquota) {
        this.bbcclientquota = bbcclientquota;
    }
    public Integer getExchangeserverquota() {
        return this.exchangeserverquota;
    }
    
    public void setExchangeserverquota(Integer exchangeserverquota) {
        this.exchangeserverquota = exchangeserverquota;
    }
    public Integer getExchangemailboxquota() {
        return this.exchangemailboxquota;
    }
    
    public void setExchangemailboxquota(Integer exchangemailboxquota) {
        this.exchangemailboxquota = exchangemailboxquota;
    }
    public Integer getSqlserverquota() {
        return this.sqlserverquota;
    }
    
    public void setSqlserverquota(Integer sqlserverquota) {
        this.sqlserverquota = sqlserverquota;
    }
    public Integer getOraclequota() {
        return this.oraclequota;
    }
    
    public void setOraclequota(Integer oraclequota) {
        this.oraclequota = oraclequota;
    }
    public Integer getMysqlquota() {
        return this.mysqlquota;
    }
    
    public void setMysqlquota(Integer mysqlquota) {
        this.mysqlquota = mysqlquota;
    }
    public Integer getLotusdominoquota() {
        return this.lotusdominoquota;
    }
    
    public void setLotusdominoquota(Integer lotusdominoquota) {
        this.lotusdominoquota = lotusdominoquota;
    }
    public Integer getLotusnotesquota() {
        return this.lotusnotesquota;
    }
    
    public void setLotusnotesquota(Integer lotusnotesquota) {
        this.lotusnotesquota = lotusnotesquota;
    }
    public Integer getInfiledeltaquota() {
        return this.infiledeltaquota;
    }
    
    public void setInfiledeltaquota(Integer infiledeltaquota) {
        this.infiledeltaquota = infiledeltaquota;
    }
    public Integer getVolumshadowcopyquota() {
        return this.volumshadowcopyquota;
    }
    
    public void setVolumshadowcopyquota(Integer volumshadowcopyquota) {
        this.volumshadowcopyquota = volumshadowcopyquota;
    }
    public Boolean getBosreplicationmodule() {
        return this.bosreplicationmodule;
    }
    
    public void setBosreplicationmodule(Boolean bosreplicationmodule) {
        this.bosreplicationmodule = bosreplicationmodule;
    }
    public Date getExpirydate() {
        return this.expirydate;
    }
    
    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }
    public Date getFreeupgradeuntil() {
        return this.freeupgradeuntil;
    }
    
    public void setFreeupgradeuntil(Date freeupgradeuntil) {
        this.freeupgradeuntil = freeupgradeuntil;
    }




}


