package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private Integer logid;
     private Client client;
     private Date datetime;
     private String message;
     private Integer type;
     private Integer backupitemid;
     private Integer restoreitemid;
     private Integer backupid;
     private Integer restoreid;

    public Log() {
    }

    public Log(Client client, Date datetime, String message, Integer type, Integer backupitemid, Integer restoreitemid, Integer backupid, Integer restoreid) {
       this.client = client;
       this.datetime = datetime;
       this.message = message;
       this.type = type;
       this.backupitemid = backupitemid;
       this.restoreitemid = restoreitemid;
       this.backupid = backupid;
       this.restoreid = restoreid;
    }
   
    public Integer getLogid() {
        return this.logid;
    }
    
    public void setLogid(Integer logid) {
        this.logid = logid;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public Integer getBackupitemid() {
        return this.backupitemid;
    }
    
    public void setBackupitemid(Integer backupitemid) {
        this.backupitemid = backupitemid;
    }
    public Integer getRestoreitemid() {
        return this.restoreitemid;
    }
    
    public void setRestoreitemid(Integer restoreitemid) {
        this.restoreitemid = restoreitemid;
    }
    public Integer getBackupid() {
        return this.backupid;
    }
    
    public void setBackupid(Integer backupid) {
        this.backupid = backupid;
    }
    public Integer getRestoreid() {
        return this.restoreid;
    }
    
    public void setRestoreid(Integer restoreid) {
        this.restoreid = restoreid;
    }




}


