package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1



/**
 * Longname generated by hbm2java
 */
public class Longname  implements java.io.Serializable {


     private Integer nameid;
     private int clientid;
     private String name;

    public Longname() {
    }

	
    public Longname(int clientid) {
        this.clientid = clientid;
    }
    public Longname(int clientid, String name) {
       this.clientid = clientid;
       this.name = name;
    }
   
    public Integer getNameid() {
        return this.nameid;
    }
    
    public void setNameid(Integer nameid) {
        this.nameid = nameid;
    }
    public int getClientid() {
        return this.clientid;
    }
    
    public void setClientid(int clientid) {
        this.clientid = clientid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


