package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1



/**
 * ReluserModule generated by hbm2java
 */
public class ReluserModule  implements java.io.Serializable {


     private Integer reluserModuleid;
     private Module module;
     private User user;

    public ReluserModule() {
    }

    public ReluserModule(Module module, User user) {
       this.module = module;
       this.user = user;
    }
   
    public Integer getReluserModuleid() {
        return this.reluserModuleid;
    }
    
    public void setReluserModuleid(Integer reluserModuleid) {
        this.reluserModuleid = reluserModuleid;
    }
    public Module getModule() {
        return this.module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


