package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1



/**
 * ReluserAdgroup generated by hbm2java
 */
public class ReluserAdgroup  implements java.io.Serializable {


     private Integer reluserAdgroupid;
     private Adgroup adgroup;
     private User user;

    public ReluserAdgroup() {
    }

    public ReluserAdgroup(Adgroup adgroup, User user) {
       this.adgroup = adgroup;
       this.user = user;
    }
   
    public Integer getReluserAdgroupid() {
        return this.reluserAdgroupid;
    }
    
    public void setReluserAdgroupid(Integer reluserAdgroupid) {
        this.reluserAdgroupid = reluserAdgroupid;
    }
    public Adgroup getAdgroup() {
        return this.adgroup;
    }
    
    public void setAdgroup(Adgroup adgroup) {
        this.adgroup = adgroup;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


