package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Restoreitem generated by hbm2java
 */
public class Restoreitem  implements java.io.Serializable {


     private Integer restoreitemid;
     private Status status;
     private Backupitem backupitem;
     private Restore restore;
     private String path;
     private Short type;
     private Date datetime;
     private Integer backupid;

    public Restoreitem() {
    }

    public Restoreitem(Status status, Backupitem backupitem, Restore restore, String path, Short type, Date datetime, Integer backupid) {
       this.status = status;
       this.backupitem = backupitem;
       this.restore = restore;
       this.path = path;
       this.type = type;
       this.datetime = datetime;
       this.backupid = backupid;
    }
   
    public Integer getRestoreitemid() {
        return this.restoreitemid;
    }
    
    public void setRestoreitemid(Integer restoreitemid) {
        this.restoreitemid = restoreitemid;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public Backupitem getBackupitem() {
        return this.backupitem;
    }
    
    public void setBackupitem(Backupitem backupitem) {
        this.backupitem = backupitem;
    }
    public Restore getRestore() {
        return this.restore;
    }
    
    public void setRestore(Restore restore) {
        this.restore = restore;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public Short getType() {
        return this.type;
    }
    
    public void setType(Short type) {
        this.type = type;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public Integer getBackupid() {
        return this.backupid;
    }
    
    public void setBackupid(Integer backupid) {
        this.backupid = backupid;
    }




}


