package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Settings generated by hbm2java
 */
public class Settings  implements java.io.Serializable {


     private Integer settingsid;
     private Language language;
     private String smtpserver;
     private String smtplogin;
     private String smtppassword;
     private String reportsendername;
     private String reportsenderemail;
     private Boolean sendwelcomeemail;
     private Boolean sendpasswordinemail;
     private Boolean permissionsretention;
     private Boolean movedretention;
     private Boolean enablefreetrial;
     private Integer freetrialquota;
     private Integer ftsuspendafterdays;
     private Integer ftremoveafterdays;
     private Boolean proxytype;
     private String proxyhost;
     private Integer proxyport;
     private String proxyusername;
     private String proxypassword;
     private Boolean useproxy;
     private Boolean usead;
     private String addomainname;
     private String addomaincontrollerip;
     private Boolean removeuserwhendeletedfromad;
     private Boolean removeuserwhendisabledinad;
     private Integer removeuserwhendeletedfromaddays;
     private Integer removeuserwhendeletedinaddays;
     private Boolean enablereplication;
     private String replicationusername;
     private String replicationpassword;
     private String replicationhost;
     private Integer replicationport;
     private Integer infiledeltablocksize;
     private Integer minimumfilesize;
     private String userhome;
     private Integer ftmailboxes;
     private Set trialmodulesettingses = new HashSet(0);
     private Set trialmodulesettingses_1 = new HashSet(0);
     private Set languagesettingses = new HashSet(0);
     private Set languagesettingses_1 = new HashSet(0);

    public Settings() {
    }

	
    public Settings(Language language) {
        this.language = language;
    }
    public Settings(Language language, String smtpserver, String smtplogin, String smtppassword, String reportsendername, String reportsenderemail, Boolean sendwelcomeemail, Boolean sendpasswordinemail, Boolean permissionsretention, Boolean movedretention, Boolean enablefreetrial, Integer freetrialquota, Integer ftsuspendafterdays, Integer ftremoveafterdays, Boolean proxytype, String proxyhost, Integer proxyport, String proxyusername, String proxypassword, Boolean useproxy, Boolean usead, String addomainname, String addomaincontrollerip, Boolean removeuserwhendeletedfromad, Boolean removeuserwhendisabledinad, Integer removeuserwhendeletedfromaddays, Integer removeuserwhendeletedinaddays, Boolean enablereplication, String replicationusername, String replicationpassword, String replicationhost, Integer replicationport, Integer infiledeltablocksize, Integer minimumfilesize, String userhome, Integer ftmailboxes, Set trialmodulesettingses, Set trialmodulesettingses_1, Set languagesettingses, Set languagesettingses_1) {
       this.language = language;
       this.smtpserver = smtpserver;
       this.smtplogin = smtplogin;
       this.smtppassword = smtppassword;
       this.reportsendername = reportsendername;
       this.reportsenderemail = reportsenderemail;
       this.sendwelcomeemail = sendwelcomeemail;
       this.sendpasswordinemail = sendpasswordinemail;
       this.permissionsretention = permissionsretention;
       this.movedretention = movedretention;
       this.enablefreetrial = enablefreetrial;
       this.freetrialquota = freetrialquota;
       this.ftsuspendafterdays = ftsuspendafterdays;
       this.ftremoveafterdays = ftremoveafterdays;
       this.proxytype = proxytype;
       this.proxyhost = proxyhost;
       this.proxyport = proxyport;
       this.proxyusername = proxyusername;
       this.proxypassword = proxypassword;
       this.useproxy = useproxy;
       this.usead = usead;
       this.addomainname = addomainname;
       this.addomaincontrollerip = addomaincontrollerip;
       this.removeuserwhendeletedfromad = removeuserwhendeletedfromad;
       this.removeuserwhendisabledinad = removeuserwhendisabledinad;
       this.removeuserwhendeletedfromaddays = removeuserwhendeletedfromaddays;
       this.removeuserwhendeletedinaddays = removeuserwhendeletedinaddays;
       this.enablereplication = enablereplication;
       this.replicationusername = replicationusername;
       this.replicationpassword = replicationpassword;
       this.replicationhost = replicationhost;
       this.replicationport = replicationport;
       this.infiledeltablocksize = infiledeltablocksize;
       this.minimumfilesize = minimumfilesize;
       this.userhome = userhome;
       this.ftmailboxes = ftmailboxes;
       this.trialmodulesettingses = trialmodulesettingses;
       this.trialmodulesettingses_1 = trialmodulesettingses_1;
       this.languagesettingses = languagesettingses;
       this.languagesettingses_1 = languagesettingses_1;
    }
   
    public Integer getSettingsid() {
        return this.settingsid;
    }
    
    public void setSettingsid(Integer settingsid) {
        this.settingsid = settingsid;
    }
    public Language getLanguage() {
        return this.language;
    }
    
    public void setLanguage(Language language) {
        this.language = language;
    }
    public String getSmtpserver() {
        return this.smtpserver;
    }
    
    public void setSmtpserver(String smtpserver) {
        this.smtpserver = smtpserver;
    }
    public String getSmtplogin() {
        return this.smtplogin;
    }
    
    public void setSmtplogin(String smtplogin) {
        this.smtplogin = smtplogin;
    }
    public String getSmtppassword() {
        return this.smtppassword;
    }
    
    public void setSmtppassword(String smtppassword) {
        this.smtppassword = smtppassword;
    }
    public String getReportsendername() {
        return this.reportsendername;
    }
    
    public void setReportsendername(String reportsendername) {
        this.reportsendername = reportsendername;
    }
    public String getReportsenderemail() {
        return this.reportsenderemail;
    }
    
    public void setReportsenderemail(String reportsenderemail) {
        this.reportsenderemail = reportsenderemail;
    }
    public Boolean getSendwelcomeemail() {
        return this.sendwelcomeemail;
    }
    
    public void setSendwelcomeemail(Boolean sendwelcomeemail) {
        this.sendwelcomeemail = sendwelcomeemail;
    }
    public Boolean getSendpasswordinemail() {
        return this.sendpasswordinemail;
    }
    
    public void setSendpasswordinemail(Boolean sendpasswordinemail) {
        this.sendpasswordinemail = sendpasswordinemail;
    }
    public Boolean getPermissionsretention() {
        return this.permissionsretention;
    }
    
    public void setPermissionsretention(Boolean permissionsretention) {
        this.permissionsretention = permissionsretention;
    }
    public Boolean getMovedretention() {
        return this.movedretention;
    }
    
    public void setMovedretention(Boolean movedretention) {
        this.movedretention = movedretention;
    }
    public Boolean getEnablefreetrial() {
        return this.enablefreetrial;
    }
    
    public void setEnablefreetrial(Boolean enablefreetrial) {
        this.enablefreetrial = enablefreetrial;
    }
    public Integer getFreetrialquota() {
        return this.freetrialquota;
    }
    
    public void setFreetrialquota(Integer freetrialquota) {
        this.freetrialquota = freetrialquota;
    }
    public Integer getFtsuspendafterdays() {
        return this.ftsuspendafterdays;
    }
    
    public void setFtsuspendafterdays(Integer ftsuspendafterdays) {
        this.ftsuspendafterdays = ftsuspendafterdays;
    }
    public Integer getFtremoveafterdays() {
        return this.ftremoveafterdays;
    }
    
    public void setFtremoveafterdays(Integer ftremoveafterdays) {
        this.ftremoveafterdays = ftremoveafterdays;
    }
    public Boolean getProxytype() {
        return this.proxytype;
    }
    
    public void setProxytype(Boolean proxytype) {
        this.proxytype = proxytype;
    }
    public String getProxyhost() {
        return this.proxyhost;
    }
    
    public void setProxyhost(String proxyhost) {
        this.proxyhost = proxyhost;
    }
    public Integer getProxyport() {
        return this.proxyport;
    }
    
    public void setProxyport(Integer proxyport) {
        this.proxyport = proxyport;
    }
    public String getProxyusername() {
        return this.proxyusername;
    }
    
    public void setProxyusername(String proxyusername) {
        this.proxyusername = proxyusername;
    }
    public String getProxypassword() {
        return this.proxypassword;
    }
    
    public void setProxypassword(String proxypassword) {
        this.proxypassword = proxypassword;
    }
    public Boolean getUseproxy() {
        return this.useproxy;
    }
    
    public void setUseproxy(Boolean useproxy) {
        this.useproxy = useproxy;
    }
    public Boolean getUsead() {
        return this.usead;
    }
    
    public void setUsead(Boolean usead) {
        this.usead = usead;
    }
    public String getAddomainname() {
        return this.addomainname;
    }
    
    public void setAddomainname(String addomainname) {
        this.addomainname = addomainname;
    }
    public String getAddomaincontrollerip() {
        return this.addomaincontrollerip;
    }
    
    public void setAddomaincontrollerip(String addomaincontrollerip) {
        this.addomaincontrollerip = addomaincontrollerip;
    }
    public Boolean getRemoveuserwhendeletedfromad() {
        return this.removeuserwhendeletedfromad;
    }
    
    public void setRemoveuserwhendeletedfromad(Boolean removeuserwhendeletedfromad) {
        this.removeuserwhendeletedfromad = removeuserwhendeletedfromad;
    }
    public Boolean getRemoveuserwhendisabledinad() {
        return this.removeuserwhendisabledinad;
    }
    
    public void setRemoveuserwhendisabledinad(Boolean removeuserwhendisabledinad) {
        this.removeuserwhendisabledinad = removeuserwhendisabledinad;
    }
    public Integer getRemoveuserwhendeletedfromaddays() {
        return this.removeuserwhendeletedfromaddays;
    }
    
    public void setRemoveuserwhendeletedfromaddays(Integer removeuserwhendeletedfromaddays) {
        this.removeuserwhendeletedfromaddays = removeuserwhendeletedfromaddays;
    }
    public Integer getRemoveuserwhendeletedinaddays() {
        return this.removeuserwhendeletedinaddays;
    }
    
    public void setRemoveuserwhendeletedinaddays(Integer removeuserwhendeletedinaddays) {
        this.removeuserwhendeletedinaddays = removeuserwhendeletedinaddays;
    }
    public Boolean getEnablereplication() {
        return this.enablereplication;
    }
    
    public void setEnablereplication(Boolean enablereplication) {
        this.enablereplication = enablereplication;
    }
    public String getReplicationusername() {
        return this.replicationusername;
    }
    
    public void setReplicationusername(String replicationusername) {
        this.replicationusername = replicationusername;
    }
    public String getReplicationpassword() {
        return this.replicationpassword;
    }
    
    public void setReplicationpassword(String replicationpassword) {
        this.replicationpassword = replicationpassword;
    }
    public String getReplicationhost() {
        return this.replicationhost;
    }
    
    public void setReplicationhost(String replicationhost) {
        this.replicationhost = replicationhost;
    }
    public Integer getReplicationport() {
        return this.replicationport;
    }
    
    public void setReplicationport(Integer replicationport) {
        this.replicationport = replicationport;
    }
    public Integer getInfiledeltablocksize() {
        return this.infiledeltablocksize;
    }
    
    public void setInfiledeltablocksize(Integer infiledeltablocksize) {
        this.infiledeltablocksize = infiledeltablocksize;
    }
    public Integer getMinimumfilesize() {
        return this.minimumfilesize;
    }
    
    public void setMinimumfilesize(Integer minimumfilesize) {
        this.minimumfilesize = minimumfilesize;
    }
    public String getUserhome() {
        return this.userhome;
    }
    
    public void setUserhome(String userhome) {
        this.userhome = userhome;
    }
    public Integer getFtmailboxes() {
        return this.ftmailboxes;
    }
    
    public void setFtmailboxes(Integer ftmailboxes) {
        this.ftmailboxes = ftmailboxes;
    }
    public Set getTrialmodulesettingses() {
        return this.trialmodulesettingses;
    }
    
    public void setTrialmodulesettingses(Set trialmodulesettingses) {
        this.trialmodulesettingses = trialmodulesettingses;
    }
    public Set getTrialmodulesettingses_1() {
        return this.trialmodulesettingses_1;
    }
    
    public void setTrialmodulesettingses_1(Set trialmodulesettingses_1) {
        this.trialmodulesettingses_1 = trialmodulesettingses_1;
    }
    public Set getLanguagesettingses() {
        return this.languagesettingses;
    }
    
    public void setLanguagesettingses(Set languagesettingses) {
        this.languagesettingses = languagesettingses;
    }
    public Set getLanguagesettingses_1() {
        return this.languagesettingses_1;
    }
    
    public void setLanguagesettingses_1(Set languagesettingses_1) {
        this.languagesettingses_1 = languagesettingses_1;
    }




}


