package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private int statusid;
     private String name;
     private Set restores = new HashSet(0);
     private Set backups = new HashSet(0);
     private Set backups_1 = new HashSet(0);
     private Set restores_1 = new HashSet(0);
     private Set restoreitems = new HashSet(0);
     private Set restoreitems_1 = new HashSet(0);

    public Status() {
    }

	
    public Status(int statusid) {
        this.statusid = statusid;
    }
    public Status(int statusid, String name, Set restores, Set backups, Set backups_1, Set restores_1, Set restoreitems, Set restoreitems_1) {
       this.statusid = statusid;
       this.name = name;
       this.restores = restores;
       this.backups = backups;
       this.backups_1 = backups_1;
       this.restores_1 = restores_1;
       this.restoreitems = restoreitems;
       this.restoreitems_1 = restoreitems_1;
    }
   
    public int getStatusid() {
        return this.statusid;
    }
    
    public void setStatusid(int statusid) {
        this.statusid = statusid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getRestores() {
        return this.restores;
    }
    
    public void setRestores(Set restores) {
        this.restores = restores;
    }
    public Set getBackups() {
        return this.backups;
    }
    
    public void setBackups(Set backups) {
        this.backups = backups;
    }
    public Set getBackups_1() {
        return this.backups_1;
    }
    
    public void setBackups_1(Set backups_1) {
        this.backups_1 = backups_1;
    }
    public Set getRestores_1() {
        return this.restores_1;
    }
    
    public void setRestores_1(Set restores_1) {
        this.restores_1 = restores_1;
    }
    public Set getRestoreitems() {
        return this.restoreitems;
    }
    
    public void setRestoreitems(Set restoreitems) {
        this.restoreitems = restoreitems;
    }
    public Set getRestoreitems_1() {
        return this.restoreitems_1;
    }
    
    public void setRestoreitems_1(Set restoreitems_1) {
        this.restoreitems_1 = restoreitems_1;
    }




}


