package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Storageusage generated by hbm2java
 */
public class Storageusage  implements java.io.Serializable {


     private Integer storageusageid;
     private User user;
     private Date date;
     private Integer data;
     private Integer uploaded;

    public Storageusage() {
    }

	
    public Storageusage(User user) {
        this.user = user;
    }
    public Storageusage(User user, Date date, Integer data, Integer uploaded) {
       this.user = user;
       this.date = date;
       this.data = data;
       this.uploaded = uploaded;
    }
   
    public Integer getStorageusageid() {
        return this.storageusageid;
    }
    
    public void setStorageusageid(Integer storageusageid) {
        this.storageusageid = storageusageid;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getData() {
        return this.data;
    }
    
    public void setData(Integer data) {
        this.data = data;
    }
    public Integer getUploaded() {
        return this.uploaded;
    }
    
    public void setUploaded(Integer uploaded) {
        this.uploaded = uploaded;
    }




}


