package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1



/**
 * Trialmodulesettings generated by hbm2java
 */
public class Trialmodulesettings  implements java.io.Serializable {


     private Integer trialmodulesettingsid;
     private Settings settings;
     private Module module;

    public Trialmodulesettings() {
    }

    public Trialmodulesettings(Settings settings, Module module) {
       this.settings = settings;
       this.module = module;
    }
   
    public Integer getTrialmodulesettingsid() {
        return this.trialmodulesettingsid;
    }
    
    public void setTrialmodulesettingsid(Integer trialmodulesettingsid) {
        this.trialmodulesettingsid = trialmodulesettingsid;
    }
    public Settings getSettings() {
        return this.settings;
    }
    
    public void setSettings(Settings settings) {
        this.settings = settings;
    }
    public Module getModule() {
        return this.module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }




}


