package net.nettape.dal.object;
// Generated 11-jan-2012 20:37:05 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userid;
     private Server server;
     private String username;
     private String password;
     private String name;
     private String firstname;
     private Date datecreated;
     private Date datedeleted;
     private Date datedeactivated;
     private Boolean active;
     private Boolean deleted;
     private Long quota;
     private Long bandwidth;
     private Integer languageid;
     private String timezone;
     private String notes;
     private Short backupclient;
     private Boolean freetrial;
     private String email;
     private Short type;
     private Date datetodeactivate;
     private Integer maxclients;
     private Integer ftmailboxes;
     private Set reluserAdgroups = new HashSet(0);
     private Set clients = new HashSet(0);
     private Set reluserModules = new HashSet(0);
     private Set clients_1 = new HashSet(0);
     private Set storageusages = new HashSet(0);
     private Set reluserModules_1 = new HashSet(0);
     private Set reluserAdgroups_1 = new HashSet(0);
     private Set storageusages_1 = new HashSet(0);
     private Set contacts = new HashSet(0);
     private Set contacts_1 = new HashSet(0);

    public User() {
    }

    public User(Server server, String username, String password, String name, String firstname, Date datecreated, Date datedeleted, Date datedeactivated, Boolean active, Boolean deleted, Long quota, Long bandwidth, Integer languageid, String timezone, String notes, Short backupclient, Boolean freetrial, String email, Short type, Date datetodeactivate, Integer maxclients, Integer ftmailboxes, Set reluserAdgroups, Set clients, Set reluserModules, Set clients_1, Set storageusages, Set reluserModules_1, Set reluserAdgroups_1, Set storageusages_1, Set contacts, Set contacts_1) {
       this.server = server;
       this.username = username;
       this.password = password;
       this.name = name;
       this.firstname = firstname;
       this.datecreated = datecreated;
       this.datedeleted = datedeleted;
       this.datedeactivated = datedeactivated;
       this.active = active;
       this.deleted = deleted;
       this.quota = quota;
       this.bandwidth = bandwidth;
       this.languageid = languageid;
       this.timezone = timezone;
       this.notes = notes;
       this.backupclient = backupclient;
       this.freetrial = freetrial;
       this.email = email;
       this.type = type;
       this.datetodeactivate = datetodeactivate;
       this.maxclients = maxclients;
       this.ftmailboxes = ftmailboxes;
       this.reluserAdgroups = reluserAdgroups;
       this.clients = clients;
       this.reluserModules = reluserModules;
       this.clients_1 = clients_1;
       this.storageusages = storageusages;
       this.reluserModules_1 = reluserModules_1;
       this.reluserAdgroups_1 = reluserAdgroups_1;
       this.storageusages_1 = storageusages_1;
       this.contacts = contacts;
       this.contacts_1 = contacts_1;
    }
   
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
    public Server getServer() {
        return this.server;
    }
    
    public void setServer(Server server) {
        this.server = server;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public Date getDatecreated() {
        return this.datecreated;
    }
    
    public void setDatecreated(Date datecreated) {
        this.datecreated = datecreated;
    }
    public Date getDatedeleted() {
        return this.datedeleted;
    }
    
    public void setDatedeleted(Date datedeleted) {
        this.datedeleted = datedeleted;
    }
    public Date getDatedeactivated() {
        return this.datedeactivated;
    }
    
    public void setDatedeactivated(Date datedeactivated) {
        this.datedeactivated = datedeactivated;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Boolean getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
    public Long getQuota() {
        return this.quota;
    }
    
    public void setQuota(Long quota) {
        this.quota = quota;
    }
    public Long getBandwidth() {
        return this.bandwidth;
    }
    
    public void setBandwidth(Long bandwidth) {
        this.bandwidth = bandwidth;
    }
    public Integer getLanguageid() {
        return this.languageid;
    }
    
    public void setLanguageid(Integer languageid) {
        this.languageid = languageid;
    }
    public String getTimezone() {
        return this.timezone;
    }
    
    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public Short getBackupclient() {
        return this.backupclient;
    }
    
    public void setBackupclient(Short backupclient) {
        this.backupclient = backupclient;
    }
    public Boolean getFreetrial() {
        return this.freetrial;
    }
    
    public void setFreetrial(Boolean freetrial) {
        this.freetrial = freetrial;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Short getType() {
        return this.type;
    }
    
    public void setType(Short type) {
        this.type = type;
    }
    public Date getDatetodeactivate() {
        return this.datetodeactivate;
    }
    
    public void setDatetodeactivate(Date datetodeactivate) {
        this.datetodeactivate = datetodeactivate;
    }
    public Integer getMaxclients() {
        return this.maxclients;
    }
    
    public void setMaxclients(Integer maxclients) {
        this.maxclients = maxclients;
    }
    public Integer getFtmailboxes() {
        return this.ftmailboxes;
    }
    
    public void setFtmailboxes(Integer ftmailboxes) {
        this.ftmailboxes = ftmailboxes;
    }
    public Set getReluserAdgroups() {
        return this.reluserAdgroups;
    }
    
    public void setReluserAdgroups(Set reluserAdgroups) {
        this.reluserAdgroups = reluserAdgroups;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }
    public Set getReluserModules() {
        return this.reluserModules;
    }
    
    public void setReluserModules(Set reluserModules) {
        this.reluserModules = reluserModules;
    }
    public Set getClients_1() {
        return this.clients_1;
    }
    
    public void setClients_1(Set clients_1) {
        this.clients_1 = clients_1;
    }
    public Set getStorageusages() {
        return this.storageusages;
    }
    
    public void setStorageusages(Set storageusages) {
        this.storageusages = storageusages;
    }
    public Set getReluserModules_1() {
        return this.reluserModules_1;
    }
    
    public void setReluserModules_1(Set reluserModules_1) {
        this.reluserModules_1 = reluserModules_1;
    }
    public Set getReluserAdgroups_1() {
        return this.reluserAdgroups_1;
    }
    
    public void setReluserAdgroups_1(Set reluserAdgroups_1) {
        this.reluserAdgroups_1 = reluserAdgroups_1;
    }
    public Set getStorageusages_1() {
        return this.storageusages_1;
    }
    
    public void setStorageusages_1(Set storageusages_1) {
        this.storageusages_1 = storageusages_1;
    }
    public Set getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Set contacts) {
        this.contacts = contacts;
    }
    public Set getContacts_1() {
        return this.contacts_1;
    }
    
    public void setContacts_1(Set contacts_1) {
        this.contacts_1 = contacts_1;
    }




}


